### ISSUE TITLE
how to use this library?

### ISSUE THREAD

**Issue by iamDonkey** [andrew-ld/LL-mtproto#1]
This library is ready to use or under development?

**Comment by andrew-ld** [comment]
It depends on what you want to use it for.

if you want to keep sessions only to call mtproto methods my library is a good solution because it uses very few resources.

if you want to safely receive messages from telegram i don't guarantee anything because you have to implement methods to retrieve old messages and i don't think i will ever do that because my library is to be used as a core of a more extended client.

**Comment by iamDonkey** [comment]
What about login with phone number?
Because some methods can't be run as bot.

**Comment by iamDonkey** [comment]
```
python3 test.py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    from ll_mtproto import Client, TelegramSchema, AuthKey, TelegramDatacenter
  File "/root/LL-mtproto-master/ll_mtproto/__init__.py", line 2, in <module>
    from .client import Client
  File "/root/LL-mtproto-master/ll_mtproto/client.py", line 11, in <module>
    from .network import mtproto
  File "/root/LL-mtproto-master/ll_mtproto/network/mtproto.py", line 12, in <module>
    from . import encryption
  File "/root/LL-mtproto-master/ll_mtproto/network/encryption.py", line 8, in <module>
    from ..tl.byteutils import (
  File "/root/LL-mtproto-master/ll_mtproto/tl/byteutils.py", line 41, in <module>
    def base64decode(s: str | bytes) -> bytes:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

i am getting this error.
python version 3.8.10

**Comment by andrew-ld** [comment]
support only python 3.10

**Comment by BaseMax** [comment]
What about **Python 3.11**?

**Comment by andrew-ld** [comment]
@BaseMax I will support it when it reaches archlinux.

**Comment by BaseMax** [comment]
> @BaseMax I will support it when it reaches archlinux.

**Python 3.11** is available via `yay` and you can easily install it on Arch-base distros.
https://aur.archlinux.org/packages/python311

P.S: I am not sure when it will be publicly available in the official package manager.

**Comment by andrew-ld** [comment]
@BaseMax I verified and it seems that there is no breaking changes affecting my library, however with release on archlinux obviously meant on the official repo.

**Comment by andrew-ld** [comment]
What about login with phone number?

@iamDonkey https://gist.github.com/andrew-ld/77bdf595bae41ec685664fe5b14779e1

**Comment by iamDonkey** [comment]
Wow thanks 👍. No support for 2FA?

**Comment by andrew-ld** [comment]
you are free to implement it according to the telegram specifications, I can't work on all the high level details of the client, the point is that the client should not handle these things internally but give the user the power to do what he wants with this client

**Comment by iamDonkey** [comment]
Any reason to choose python for this project?
