### ISSUE TITLE
layer 140

### ISSUE THREAD

**Issue by andrew-ld** [andrew-ld/LL-mtproto#3]
layer 140 add a costructor with multiple flags, need investigation

**Comment by cavallium** [comment]
pac

**Comment by andrew-ld** [comment]
[iamDonkey](https://github.com/iamDonkey) if you update to the latest commit, can you let me know if you experience problems with the de/seralisation of data, I have modified the de/seralisation to support multiple bitsets that are present from layer 140

**Comment by iamDonkey** [comment]
Yes sure Andrew. Any performance boost with this update?

**Comment by iamDonkey** [comment]
i tested with my application, and i did not encounter any issue. i just want to know if there any improvements in terms of speed with this update.

**Comment by andrew-ld** [comment]
no, I only added support for the new telegram versions
