### ISSUE TITLE
response to json

### ISSUE THREAD

**Issue by iamDonkey** [andrew-ld/LL-mtproto#6]
when i try to convert received response into json string i am getting this following error.

TypeError: Object of type bytes is not JSON serializable

```
dialogs = await session.rpc_call({"_cons":"messages.getDialogs","hash":0,"offset_peer": {"_cons":"inputPeerEmpty"},"offset_id":0, "offset_date":0,"offset": 0, "max_id": 0,"limit": 3,})
print(json.dumps(dialogs.get_dict()))
```

**Comment by andrew-ld** [comment]
because json does not accept bytes, a custom codec should be implemented

```
def _hexify_bytes(data: any) -> any:
   if isinstance(data, bytes):
       return data.hex()
   return data

print(json.dumps(dialogs.get_dict(), default=_hexify_bytes))
```

**Comment by iamDonkey** [comment]
it works. and thanks for the help.

**Comment by iamDonkey** [comment]
Hi @andrew-ld
 In response all strings are coming as bytes perhaps we need to change this line https://github.com/andrew-ld/LL-mtproto/blob/b654c3410bd957dfe3007b991c505e2359ef8a5d/ll_mtproto/tl/byteutils.py#L189 to return string.decode('UTF-8') ?

**Comment by iamDonkey** [comment]
https://github.com/andrew-ld/LL-mtproto/blob/b654c3410bd957dfe3007b991c505e2359ef8a5d/ll_mtproto/tl/tl.py#L557
I see here same function used to unpack both bytes and string.

**Comment by iamDonkey** [comment]
So changing this line https://github.com/andrew-ld/LL-mtproto/blob/b654c3410bd957dfe3007b991c505e2359ef8a5d/ll_mtproto/tl/tl.py#L555
To unpack_binary_string(bytereader).decode('UTF-8')  could be the correct way?

**Comment by andrew-ld** [comment]
don't want to unnecessarily decode strings, I don't know whether to add this feature or not, also because in my software a good portion of the strings are not used.

**Comment by andrew-ld** [comment]
the best thing would be to make it configurable

**Comment by iamDonkey** [comment]
> don't want to unnecessarily decode strings, I don't know whether to add this feature or not, also because in my software a good portion of the strings are not used.

I think response should match the data type specified in the telegram TL. I mean the .tl file.

**Comment by andrew-ld** [comment]
done, try now

**Comment by iamDonkey** [comment]
works good. 👍
