### ISSUE TITLE
received a message with unknown salt!

### ISSUE THREAD

**Issue by iamDonkey** [andrew-ld/LL-mtproto#8]
in a long, continuously running process after some period of time,  i start to get this error message, 
same error for all rpc call.
```
ERROR:root:received a message with unknown salt! -259348346848177331
ERROR:root:received a message with unknown salt! -259348346848177331
ERROR:root:received a message with unknown salt! -259348346848177331
ERROR:root:received a message with unknown salt! -259348346848177331
```

but the response for rpc calls seems to be coming and correct 🤔 
is this related to network issue? do i have to ignore it? 
this error do not go away until i relaunch the process.

**Comment by andrew-ld** [comment]
simply after 30 minutes the session salt changes and the mtproto client requests a new one every 30 minutes + 1s, but when it receives the reply the salt has already changed, so for a single time you will have this log

**Comment by andrew-ld** [comment]
However, the salt is updated even with the receipt of bad_server_salt, which means that the mtproto server still accepts the current salt and is not forcing the mtproto client to update it, in case the server forces the update I will receive a bad_server_salt and the salt will also update in the client and for a further 30 minutes you will not get this error.

**Comment by andrew-ld** [comment]
https://github.com/andrew-ld/LL-mtproto/commit/4a38bfee457f8a0aeae595ea1415586902073dc5

I have modified how the client requests a salt from the mtproto server, I have made that if I do not receive a reply within 30 seconds I re-execute another request, so as to avoid your case where the client is left with an old server_salt because get_future_salts has not replied and still the mtproto server accepts the old salt but only replies with a new one

**Comment by andrew-ld** [comment]
@iamDonkey can try?

**Comment by iamDonkey** [comment]
> @iamDonkey can try?

I will try soon and let you know

**Comment by iamDonkey** [comment]
still getting this error endlessly i noticed it gives error around 20mins after launch.

**Comment by andrew-ld** [comment]
Can you send me debug level logs from client startup until this happens

**Comment by andrew-ld** [comment]
```
DEBUG:root:sending message (ping) 7100142388728814516 to mtproto
DEBUG:root:received message (pong) 7100142388872326145 from mtproto
DEBUG:root:pong message: -7104915902057347489
DEBUG:root:sending message (get_future_salts) 7100142502120849004 to mtproto
ERROR:root:received a message with unknown salt! -3968728431761421443
DEBUG:root:received message (future_salts) 7100142502301487105 from mtproto
DEBUG:root:scheduling get_future_salts, current salt is valid for 1801 seconds
DEBUG:root:sending message (ping) 7100142517822699240 to mtproto
DEBUG:root:received message (pong) 7100142518084425729 from mtproto
DEBUG:root:pong message: -7842307514900952248
DEBUG:root:sending message (ping) 7100142647152023740 to mtproto
DEBUG:root:received message (pong) 7100142647286887425 from mtproto
DEBUG:root:pong message: 3472225481523550895

```

**Comment by andrew-ld** [comment]
proper functioning of the client should look like this

**Comment by iamDonkey** [comment]
I am doing more tests  i will post update soon.

**Comment by iamDonkey** [comment]
hi @andrew-ld 
fresh log here https://pastebin.com/raw/sMZxy1Gk
this time error came after 24mins
running another test and will post result in next 30 mins.

**Comment by iamDonkey** [comment]
another log https://pastebin.com/raw/fWZC0Fdm
this time error came in 21mins but it must be noted that same error was printed at the time of client launch as well? 🤔

**Comment by iamDonkey** [comment]
https://core.telegram.org/mtproto/service_messages#request-for-several-future-salts

**Comment by andrew-ld** [comment]
The problem I'm noticing is that the salt can expire even before 30 minutes, I need to be able to handle this case, the problem is that get_future_salts apparently doesn't return the exact time of how long that salt expires so I don't actually know after how long to do it.

**Comment by iamDonkey** [comment]
{'_cons': 'future_salts', 'req_msg_id': 7100299230082561864, 'now': 1653167239, 'salts': [{'_cons': 'future_salt', 'valid_since': 1653166095, 'valid_until': 1653169695, 'salt': -7268505024579983429}, {'_cons': 'future_salt', 'valid_since': 1653167895, 'valid_until': 1653171495, 'salt': -3011236082352035825}]}

according to the received response salt has lifetime of 3600 seconds/60minutes/1hr?

**Comment by andrew-ld** [comment]
The correct solution would be to request 64 future salt and keep them pinned in the client and when I receive a message with a different salt if present in one of these future salts I have to update the salt present in the authkey with the one received

**Comment by andrew-ld** [comment]
@iamDonkey The server accepts the correct salt for 60 minutes however after 30 minutes it already no longer uses it in messages from the server to the client but still the client can continue to use it to send messages to the server, in fact if you see I have a min() in the function that calculates the expiration of the current salt

**Comment by iamDonkey** [comment]
> The correct solution would be to request 64 future salt and keep them pinned in the client and when I receive a message with a different salt if present in one of these future salts I have to update the salt present in the authkey with the one received
i think no need extra rpc calls and work. 
just replace the client side stored server salt with server returned salt silently if they are not same? and not show any warning or error. 
will that work?

**Comment by andrew-ld** [comment]
No better to check with the salts already obtained before, because this is to prevent time based Attack, and I think by doing so I would make the client vulnerable to some security bug.

**Comment by iamDonkey** [comment]
if you obtain 64 salts at the launch time how long it can run without sending `get_future_salts` i don't like sending additional calls.  so far this is the best mtproto library i ever found. it runs on memory as low as 20MB.

**Comment by andrew-ld** [comment]
keeping 64 salt in memory is almost irrelevant in total ram usage

**Comment by andrew-ld** [comment]
I use this library to keep more than 1000 bots connected in parallel without using too much ram, so it will always remain the 'main goal not to occupy more RAM than necessary

**Comment by iamDonkey** [comment]
> keeping 64 salt in memory is almost irrelevant in total ram usage

Yes but i want to know howlong these 64salts last for?

**Comment by andrew-ld** [comment]
https://github.com/andrew-ld/LL-mtproto/commit/f6720644f21e16679a534505f367ec9dab85b3c8

**Comment by andrew-ld** [comment]
from the expiry time of the salt I subtract the current time so that I know when the salt will expire and then remove 1800 seconds, basically removing the time when the salt is valid from the client to the server but not from the server to the client

**Comment by iamDonkey** [comment]
It's better now.
